"""
Part C, Task 1 — Local AI Extraction (Ollama)
Kaveri Infrasystems / Assignment Three

Reads all 26 Execution Records' Description text (the Hinglish site-log
remarks) from ClickUp, runs each through a local Ollama model asking it to
extract a delay category and delay hours, and scores the model's output
against hand_labels.csv — labels the assignment brief and I both agreed
had to be produced independently by the person, not generated by an AI,
since they're the ground truth the AI is being measured against.

Design decisions (see build_log.md for the full reasoning):
  - Runs entirely against a local Ollama model (http://localhost:11434),
    never a cloud AI API, per §8.1's "no contract data to outside AI
    services" rule — data never leaves this machine.
  - The model is explicitly instructed to output "not stated" for delay
    hours rather than infer a number from a vague phrase like "pura din"
    or "aadha din" (whole day / half day) — mirroring exactly the rule
    the hand labels themselves followed, so the comparison is apples to
    apples rather than penalising the model for something the human
    labeller was also told not to do.
  - Each extraction is written back to its execution record as a native
    ClickUp comment ("Delay extraction (<model>): category=..., delay_hours=...").
    Custom Fields are locked on this Free Plan workspace, and comments
    are not custom fields, so this costs no quota. Re-runs skip a record
    that already has a comment from the same model, and results from a
    different model are added alongside rather than replacing them.
    Failed extractions are never written. Set WRITE_BACK=false in .env
    to score without touching ClickUp.
  - Sampling is fixed (temperature 0, seed 42) so the same model gives the
    same output on every run. Without this, two runs of the same model
    scored identically overall but disagreed on 5 individual remarks, so
    a reported accuracy figure would not have been reproducible.
  - Category and hour accuracy are reported separately, since a model
    could get one right and the other wrong on the same remark — a single
    blended "accuracy" number would hide that.

Usage:
    python ollama_extraction.py

Environment (.env):
    CLICKUP_API_TOKEN=pk_...
    CLICKUP_EXECUTION_RECORDS_LIST_ID=...

Requires Ollama running locally with a pulled model, e.g.:
    ollama pull llama3.1:8b
"""

import os
import re
import sys
import csv
import json
import requests
from dotenv import load_dotenv

load_dotenv()

API_TOKEN = os.getenv("CLICKUP_API_TOKEN")
EXECUTION_RECORDS_LIST_ID = os.getenv("CLICKUP_EXECUTION_RECORDS_LIST_ID")
BASE_URL = "https://api.clickup.com/api/v2"
HEADERS = {"Authorization": API_TOKEN, "Content-Type": "application/json"}

OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1:8b")  # change if you pulled a different model

# Set WRITE_BACK=false in .env for a scoring-only run that leaves ClickUp untouched.
WRITE_BACK = os.getenv("WRITE_BACK", "true").lower() != "false"
# Set REPLACE_EXISTING=true to delete this script's earlier comments (same model) and re-post.
REPLACE_EXISTING = os.getenv("REPLACE_EXISTING", "false").lower() == "true"

CATEGORIES = ["Weather", "Permission/Authority", "Equipment Failure", "Labour Shortage",
              "Material Non-Availability", "Logistics/Traffic", "No Delay"]

PROMPT_TEMPLATE = """You are classifying a construction site log entry. The entry is written in \
Hinglish (mixed Hindi/English). Read it and extract two things:

1. category: exactly one of {categories}
2. delay_hours: the number of hours of delay this entry states, as a plain number \
(e.g. "2", "3"). If the entry does not explicitly state a number of hours — even if it implies \
a long delay with a phrase like "pura din" (whole day) or "aadha din" (half day) — you MUST \
answer "not stated". Do not estimate, convert, or guess a number for a vague duration.

Site log entry: "{remark}"

Respond with ONLY a JSON object, no other text, in exactly this form:
{{"category": "...", "delay_hours": "..."}}
"""


# ---------------------------------------------------------------------------
# ClickUp
# ---------------------------------------------------------------------------

def api_get(path, params=None):
    r = requests.get(f"{BASE_URL}{path}", headers=HEADERS, params=params)
    r.raise_for_status()
    return r.json()


def api_post(path, payload):
    r = requests.post(f"{BASE_URL}{path}", headers=HEADERS, json=payload)
    if r.status_code >= 400:
        print(f"  ! POST {path} failed: {r.status_code} {r.text}")
    r.raise_for_status()
    return r.json()


def comment_prefix():
    return f"Delay extraction ({OLLAMA_MODEL}):"


def existing_comment_ids(task_id):
    """IDs of comments on this task written by THIS script for THIS model,
    matched by the exact prefix. Comments from a different model, or by a
    person, never match, so they are never touched."""
    comments = api_get(f"/task/{task_id}/comment").get("comments", [])
    return [c["id"] for c in comments if c.get("comment_text", "").startswith(comment_prefix())]


def api_delete(path):
    r = requests.delete(f"{BASE_URL}{path}", headers=HEADERS)
    if r.status_code >= 400:
        print(f"  ! DELETE {path} failed: {r.status_code} {r.text}")
    r.raise_for_status()


def write_result_to_clickup(task_id, category, hours):
    """Posts the extraction as a native comment. Custom Fields are locked
    on this Free Plan workspace, and comments are not custom fields, so
    they cost no quota."""
    if hours == "not stated" or hours is None:
        hours_text = "not stated"
    else:
        try:
            hours_text = f"{float(hours):g} h"   # "2.0" -> "2 h", "1.5" -> "1.5 h"
        except ValueError:
            hours_text = str(hours)
    api_post(f"/task/{task_id}/comment",
             {"comment_text": f"{comment_prefix()} category={category}, delay_hours={hours_text}"})


def fetch_execution_records(list_id):
    """Returns [{"task_id", "log_id": "EX-901", "remark": "..."}], parsed
    from the Name prefix and native Description field."""
    records = []
    page = 0
    while True:
        data = api_get(f"/list/{list_id}/task", params={"page": page, "include_closed": True})
        tasks = data.get("tasks", [])
        if not tasks:
            break
        for t in tasks:
            m = re.match(r"^(EX-\d+)", t["name"])
            if not m:
                continue
            records.append({"task_id": t["id"], "log_id": m.group(1),
                            "remark": (t.get("description") or "").strip()})
        if data.get("last_page", True):
            break
        page += 1
    return records


# ---------------------------------------------------------------------------
# Ollama
# ---------------------------------------------------------------------------

def classify_with_ollama(remark):
    prompt = PROMPT_TEMPLATE.format(categories=", ".join(CATEGORIES), remark=remark)
    try:
        r = requests.post(OLLAMA_URL, json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False,
                                                "options": {"temperature": 0, "seed": 42}}, timeout=120)
        r.raise_for_status()
        raw = r.json().get("response", "")
    except requests.RequestException as e:
        print(f"  ! Ollama request failed ({e}) — is `ollama serve` running and is {OLLAMA_MODEL} pulled?")
        return None, None

    # Models sometimes wrap JSON in markdown fences or add stray text
    # despite instructions — extract the first {...} block rather than
    # assuming the whole response is clean JSON.
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        print(f"  ! Could not find JSON in model response: {raw!r}")
        return None, None
    try:
        parsed = json.loads(match.group(0))
        return parsed.get("category"), str(parsed.get("delay_hours"))
    except json.JSONDecodeError:
        print(f"  ! Model response wasn't valid JSON: {raw!r}")
        return None, None


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def normalize_hours(value):
    """'2h', '2', '2.0', '3 hrs', 'not stated', 'Not Stated' -> comparable
    form. Extracts the leading number via regex rather than stripping
    unit-word substrings in sequence, which previously mis-parsed "3 hrs"
    as "3 rs" (removing "h" broke the later "hrs" match) — caught by
    testing before this ever ran against real model output."""
    if value is None:
        return None
    v = str(value).strip().lower()
    if v in ("not stated", "notstated", "none", "n/a", ""):
        return "not stated"
    match = re.match(r"^([\d.]+)", v)
    if match:
        return str(float(match.group(1)))
    return v


def load_hand_labels(path="hand_labels.csv"):
    labels = {}
    with open(path, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            labels[row["log_id"]] = {"category": row["category"].strip(),
                                      "delay_hours": normalize_hours(row["delay_hours"])}
    return labels


def run():
    if not API_TOKEN:
        print("Set CLICKUP_API_TOKEN in .env first."); sys.exit(1)

    hand_labels = load_hand_labels()
    records = fetch_execution_records(EXECUTION_RECORDS_LIST_ID)

    results = []
    written = 0
    for rec in records:
        log_id = rec["log_id"]
        if log_id not in hand_labels:
            print(f"  ! {log_id}: no hand label found — skipped."); continue
        category, delay_hours = classify_with_ollama(rec["remark"])

        # Write the extraction back to ClickUp (task 1: "write them to
        # ClickUp"). Failed extractions are not written, so a blank or
        # made-up result never lands on a record.
        if WRITE_BACK and category is not None:
            ids = existing_comment_ids(rec["task_id"])
            if ids and not REPLACE_EXISTING:
                print(f"  {log_id}: already has a {OLLAMA_MODEL} comment, skipped "
                      f"(set REPLACE_EXISTING=true to overwrite).")
            else:
                for cid in ids:            # only this script's own comments, see existing_comment_ids
                    api_delete(f"/comment/{cid}")
                write_result_to_clickup(rec["task_id"], category, normalize_hours(delay_hours))
                written += 1

        results.append({
            "log_id": log_id, "remark": rec["remark"],
            "predicted_category": category, "predicted_hours": normalize_hours(delay_hours),
            "actual_category": hand_labels[log_id]["category"],
            "actual_hours": hand_labels[log_id]["delay_hours"],
        })

    if not results:
        print("No results — check CLICKUP_EXECUTION_RECORDS_LIST_ID and that Ollama is running.")
        return

    category_correct = sum(1 for r in results if r["predicted_category"] == r["actual_category"])
    hours_correct = sum(1 for r in results if r["predicted_hours"] == r["actual_hours"])
    n = len(results)

    print(f"\n{'log_id':8} {'predicted cat':28} {'actual cat':28} {'pred hrs':10} {'actual hrs':10} match")
    for r in results:
        cat_ok = "OK" if r["predicted_category"] == r["actual_category"] else "X"
        hrs_ok = "OK" if r["predicted_hours"] == r["actual_hours"] else "X"
        print(f"{r['log_id']:8} {str(r['predicted_category']):28} {r['actual_category']:28} "
              f"{str(r['predicted_hours']):10} {r['actual_hours']:10} cat:{cat_ok} hrs:{hrs_ok}")

    print(f"\n{'='*50}")
    print(f"Category accuracy: {category_correct}/{n} ({100*category_correct/n:.1f}%)")
    print(f"Delay-hours accuracy: {hours_correct}/{n} ({100*hours_correct/n:.1f}%)")

    with open("ollama_results.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(results[0].keys()))
        writer.writeheader()
        writer.writerows(results)
    print("\nFull results written to ollama_results.csv")
    if WRITE_BACK:
        print(f"{written} comments written to ClickUp ({OLLAMA_MODEL}).")


if __name__ == "__main__":
    run()
